---

- pipeline:
    browser:
      - name: accepts
      - name: setLocale

- scope:
    path: '/api'
    pipeline: browser
    routes:
      - resources: users
      - resource: session

- scope:
    path: '/'
    routes:
      - resource: session
      - resources:
          name: articles
          routes:
            - resources: comments
