---

pipelines:
  browser:
    - accepts
    - setLocale
  api:
    - accepts
    - setLocale

scopes:

  - path: '/api'
    pipeline: browser
    routes:
      - resources: users
      - resource: session

  - path: '/'
    pipeline: browser
    routes:
      - resource: session
      - resources:
          name: articles
          routes:
            - resources: comments
