---

pipelines:

  browser: []
    # - checkMigrations
    # - fastify-cookie
    # - accepts
    # - setLocale
    # - fetchSession
    # - fetchFlash
    # - protectFromForgery

scopes:

  - name: '/'
    pipeline: browser
    root: true
