---

default: &default
  adapter: postgresql
  # encoding: unicode

development:
  <<: *default
  database: example_development

test:
  <<: *default
  database: example_test
  username: postgres
  password: password

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
