---

root: true
plugins:
  - jest
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

ignorePatterns:
  - '**/site/*'

rules:
  no-console: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  no-unused-vars: ['error', { argsIgnorePattern: '^_', ignoreRestSiblings: true }]
  max-len:
    - 1
    - code: 120
