---

language: node_js
node_js:
  - 10

sudo: false

cache:
  directories:
    - "node_modules"

before_install:
  - npx lerna bootstrap
  - bash -c 'cd packages/nodos/__tests__/__fixtures__/app && npm install'

before_script:
  - make build

script:
  - make lint
  - make test

