---

version: '3.1'
services:
  db:
    image: postgres
  app:
    image: node:12.16.3
    command: make -C example server
    working_dir: /code
    ports:
      - "3000:3000"
    volumes:
      - yarn:/usr/local/share/.cache/yarn/v1
      - .:/code
    depends_on:
      - db

volumes:
  yarn:
