---

pipelines:

  browser:
    - checkMigrations
    - handleDbErrors
    # - protectFromForgery
    - setCurrentUser
    - fetchFlash
    # - accepts
    # - setLocale
    # - fetchSession

  api:
    # - accepts
    - setLocale

scopes:
  - name: 'api'
    pipeline: api
    routes:
      - resources: users

  - name: '/'
    pipeline: browser
    root: true
    routes:
      - resources: users
      - resources: posts
      - resource: session
      - resources:
          name: articles
          routes:
            - resources: comments
