---

pipelines:

  browser: []
    # - checkMigrations
    # - fastify-cookie
    # - accepts
    # - setLocale
    # - fetchSession
    # - fetchFlash
    # - protectFromForgery

  api:
    - accepts
    - setLocale

scopes:

  - name: 'api'
    pipeline: browser
    routes:
      - resources: users

  - name: '/'
    pipeline: browser
    root: true
    routes:
      - resources: users
      - resources: posts
      - resource: session
      - resources:
          name: articles
          routes:
            - resources: comments
