---

pipelines:

  browser:
    - checkMigrations
    # - fastify-cookie
    # - accepts
    # - setLocale
    # - fetchSession
    # - fetchFlash
    # - protectFromForgery

  api:
    - accepts
    - setLocale

scopes:

  - path: '/api'
    pipeline: browser
    routes:
      - resources: users

  - path: '/'
    pipeline: browser
    routes:
      - resources: users
      - resources: posts
      - resource: session
      - resources:
          name: articles
          routes:
            - resources: comments
