---

pipelines:

  browser: []
    # - checkMigrations
    # - fastify-cookie
    # - accepts
    # - setLocale
    # - fetchSession
    # - fetchFlash
    # - protectFromForgery

scopes:

  - path: '/'
    pipeline: browser
    routes:
      - resources: users
      - root: 'home#index'
