---

pipelines:
  browser:
    - accepts
    - setLocale
    - fastify-formbody

  api:
    - accepts
    - setLocale

scopes:
  - name: 'api'
    pipeline: browser
    root: true
    routes:
      - resources: users

  - name: 'test'
    pipeline: api

  - name: '/'
    pipeline: browser
    root: true
    routes:
      - resources:
          name: users
          only: ['show']

      - resource:
          name: session
          except: ['build']
          routes:
            - resources: tokens

      - resources:
          name: articles
          routes:
            - resources: comments
            - resource:
                name: metadata
                except: ['show']
