name: On Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Set npm handle peer dependencies
        run: |
          npm config set legacy-peer-deps true
      - name: Install deps
        run: |
          make setup
      - name: Run lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
