name: On Push

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'nodosjs/nodos'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: |
          make setup
      - name: Run lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
